# This workflow will install Python dependencies, run tests, generate coverage report and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:mc3man/mpv-tests -y
        sudo apt-get update -y
        sudo apt-get install -y mpv
        sudo apt-get install -y libmpv-dev
        python -m pip install --upgrade pip
        pip install wheel flake8 pytest pytest-cov
        lib_path=$(python3 -m site --user-site); pip install --target=$lib_path/alt_twitch python-twitch-client
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test and generate coverage report
      run: |
        pytest bin/test_all.py --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
